# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/library.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/library.proto\x12\x0b\x62ookservice\"n\n\x08\x42ookCopy\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x13\n\x0bisAvaliable\x18\x05 \x01(\x08\x12\x11\n\tcondition\x18\x06 \x01(\t\"L\n\x11SearchBookRequest\x12\x10\n\x08\x62ookName\x18\x01 \x01(\t\x12\x12\n\nbookAuthor\x18\x02 \x01(\t\x12\x11\n\tbookGenre\x18\x03 \x01(\t\"D\n\x12SearchBookResponse\x12.\n\x0f\x61valiableCopies\x18\x01 \x03(\x0b\x32\x15.bookservice.BookCopy\"I\n\x13\x43heckoutBookRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x10\n\x08\x63opyUuid\x18\x02 \x01(\t\x12\x10\n\x08loanTime\x18\x03 \x01(\x05\"^\n\x14\x43heckoutBookResponse\x12\x0e\n\x06loanId\x18\x01 \x01(\t\x12\x0f\n\x07\x64ueDate\x18\x02 \x01(\t\x12\x11\n\tbookTitle\x18\x03 \x01(\t\x12\x12\n\nbookAuthor\x18\x04 \x01(\t2\xad\x01\n\x07Library\x12M\n\nSearchBook\x12\x1e.bookservice.SearchBookRequest\x1a\x1f.bookservice.SearchBookResponse\x12S\n\x0c\x43heckoutBook\x12 .bookservice.CheckoutBookRequest\x1a!.bookservice.CheckoutBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKCOPY']._serialized_start=36
  _globals['_BOOKCOPY']._serialized_end=146
  _globals['_SEARCHBOOKREQUEST']._serialized_start=148
  _globals['_SEARCHBOOKREQUEST']._serialized_end=224
  _globals['_SEARCHBOOKRESPONSE']._serialized_start=226
  _globals['_SEARCHBOOKRESPONSE']._serialized_end=294
  _globals['_CHECKOUTBOOKREQUEST']._serialized_start=296
  _globals['_CHECKOUTBOOKREQUEST']._serialized_end=369
  _globals['_CHECKOUTBOOKRESPONSE']._serialized_start=371
  _globals['_CHECKOUTBOOKRESPONSE']._serialized_end=465
  _globals['_LIBRARY']._serialized_start=468
  _globals['_LIBRARY']._serialized_end=641
# @@protoc_insertion_point(module_scope)
